### ISSUE TITLE
n_features is not defined

### ISSUE THREAD

**Issue by IbrahimCanKALYA** [SebastianRokholt/Hybrid-Recommender-System#1]
Hi,
Firstly, thanks for your sharing, your good work.

There is an error on analysis-and-modelling.ipynb
That named: `NameError: name 'n_features' is not defined`

onCell: [24] in this code block 
`ml_algorithms = {"Linear regression": LinearRegression(), "Lasso": Lasso(alpha=1.0, max_iter=10000), 
                 "KNN_7": KNeighborsRegressor(n_neighbors=7),
                 "RFR": RandomForestRegressor(n_estimators=1000, n_jobs=3, max_features=n_features, random_state=0),
                 "SVR": SVR(C=1.0)}`

**Comment by ceejayautumn** [comment]
U can try max_features="auto"

**Comment by SebastianRokholt** [comment]
> Hi,
> Firstly, thanks for your sharing, your good work.
> 
> There is an error on analysis-and-modelling.ipynb
> That named: `NameError: name 'n_features' is not defined`
> 
> onCell: [24] in this code block
> `ml_algorithms = {"Linear regression": LinearRegression(), "Lasso": Lasso(alpha=1.0, max_iter=10000), "KNN_7": KNeighborsRegressor(n_neighbors=7), "RFR": RandomForestRegressor(n_estimators=1000, n_jobs=3, max_features=n_features, random_state=0), "SVR": SVR(C=1.0)}`

Hi, thanks for your feedback. Ceejayautumn's fix above should solve the issue.
