### ISSUE TITLE
Part 3

### ISSUE THREAD

**Issue by vosco88** [SebastianRokholt/Hybrid-Recommender-System#2]
Hi Sebastian, 

very and comprehensive resource, I did already learn a lot. Will there be part 3 released?

**Comment by SebastianRokholt** [comment]
Hi! Thank you. There might be a part three. I currently don't have a lot of free time due to my studies, but I aim to finish the predictions notebook and the project web app at some point - maybe around Christmas this year. Let me know if you have any further questions!
